./a.out zpadinton "paqefwtdjetyiytjneytjoeyjnejeyj" | cat -e; echo "résultat attendu : zpadintoqefwjy$"
./a.out ddf6vewg64f gtwthgdwthdwfteewhrtag6h4ffdhsd | cat -e; echo "résultat attendu : df6vewg4thras$"
./a.out "rien" "cette phrase ne cache rien" | cat -e; echo "résultat attendu : rienct phas$"
./a.out | cat -e; echo "résultat attendu : $"
./a.out "rien" | cat -e; echo "résultat attendu : $"